### ISSUE TITLE
Can't download manga at Mangakakalot - chapter list not showing

### ISSUE THREAD

**Issue by alexia-beep** [RedSquirrel87/manga-downloader#813] opened 2024-01-12 22:54 UTC
Chapters won't show up only a blank screen.  I tried with various manga and various links . Thanks

**Comment by RedSquirrel87** [comment] 2024-01-12 23:05
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/4dae6f26-5a74-4104-b439-2044b518fa0b)

No issue for me here, please provide more info (what links are you trying, the log file (jvm_log.txt) content, etc...)

**Comment by alexia-beep** [comment] 2024-01-13 00:38
Thank you for your swift reply. First of all thank you for this amazing
project!!! it is a life saver.

Below plase find some info regarding my problem

https://chapmanganato.to/manga-la988935 This is one of the many links that
when pasted only comes up a blank screen.

Some urls do work however for instance this one works
https://mangakakalot.com/read-yh4qm158504985679

I am just now noticing that altough i am on the same site
https://mangakakalot.com/read-yh4qm158504985679  once i search for a
particular manga it changes to https://chapmanganato.to/. Could this be the
problem?


This is the blank screen that comes up
[image: image.png]


Thank you!!

**Comment by RedSquirrel87** [comment] 2024-01-13 10:57
Yes, the program currently supports only the mangakakalot.com domain, so it does not recognize the chapmanganato.to domain as a valid input. However I can confirm you that this has already been fixed in the nightly builds and so it will support the chapmanganato.to domain in the next public release too

**Comment by alexia-beep** [comment] 2024-01-13 11:07
Thanks!!!! Looking forward to it!

**Comment by RedSquirrel87** [comment] 2024-01-15 11:29
v62 just released, it should fix this issue

**Closed by RedSquirrel87** 2024-01-15 11:29 UTC
Labels: bug

**Comment by alexia-beep** [comment] 2024-01-15 11:34
Just tested it. It's working!!! Thanks a lot!

**Comment by alexia-beep** [comment] 2026-01-21 15:29
Dear redSquirrel,
As you may already know bato has closed down. However there is a mirror
site of bato. Would you kindly add it to Jam as currently it is not in the
approved list and chapters don't load.

This is the site

https://xbat.io/

I am sending an email instead of posting on GitHub to gatekeep the site as
they have already closed down bato.

I would very much apreciate if you could help out. this means alot to me

Many thanks in advance.

Alexia

**Comment by RedSquirrel87** [comment] 2026-01-21 15:33
> Dear redSquirrel,
> As you may already know bato has closed down. However there is a mirror
> site of bato. Would you kindly add it to Jam as currently it is not in the
> approved list and chapters don't load.
> 
> This is the site
> 
> https://xbat.io/
> 
> I am sending an email instead of posting on GitHub to gatekeep the site as
> they have already closed down bato.
> 
> I would very much apreciate if you could help out. this means alot to me
> 
> Many thanks in advance.
> 
> Alexia
> […](#)

I already released the v37.9 about an hour ago that adds support for xbat.io 👍

**Comment by alexia-beep** [comment] 2026-03-25 14:23
Dear redSquirrel,

Could you kindly add the following sites to Jam as currently they are not
in the approved list or not loading chapters. Many thanks.

https://comix.to/
https://www.mangago.me/list/directory/all/1/
https://vymanga.com/
https://mangaball.net/
https://mangadex.org/

**Comment by RedSquirrel87** [comment] 2026-03-25 14:31
> Dear redSquirrel,
> 
> Could you kindly add the following sites to Jam as currently they are not
> in the approved list or not loading chapters. Many thanks.
> 
> https://comix.to/
> https://www.mangago.me/list/directory/all/1/
> https://vymanga.com/
> https://mangaball.net/
> https://mangadex.org/
> […](#)
 
Mangadex and Mangaball are already supported by the program, and I’ve just tested them again to be sure following your report. Everything appears to be working correctly on my side (I tried a couple of random manga and they downloaded without any issues):

<img width="1920" height="231" alt="Image" src="https://github.com/user-attachments/assets/7422487a-e28b-4543-b86f-f9bd14231302" />

Vymanga and Mangago are already planned and will be added in next updates 👍

As for Comix, it is currently blocked due to Cloudflare’s anti-bot protection, which cannot be bypassed at the moment. It will require the new version of the program, which is currently under development. However, if and when Cloudflare disables that protection, it will immediately start working again, since support for that site’s framework has already been implemented in the program for some time.
