### ISSUE TITLE
Bato v3 chapter title issue

### ISSUE THREAD

**Issue by bumbaras** [RedSquirrel87/manga-downloader#853] opened 2024-09-05 08:53 UTC
MangaDownloader 64.7. Application recognizes chapters titles correctly for Bato V2, but for Bato V3 it only recognizes chapters numbers. Even if titles of chapters are visible on website, there are not in application chapter list.
Example here: https://bato.to/title/81634-i-am-the-real-one

**Comment by RedSquirrel87** [comment] 2024-09-05 14:51
Thank you for reporting the issue, I'll try to fix this in next version

**Comment by RedSquirrel87** [comment] 2024-10-20 13:57
I can confirm that this issue has now been fixed in the nightly builds and will be resolved in the next public release as well 👍

**Comment by RedSquirrel87** [comment] 2024-10-21 12:27
Unfortunately, not very soon. I am currently working on a major update for the download management system, which is being completely rewritten from scratch to support highly requested features like pause/resume, priorities, individual download management with list rearrangement, etc. This will take some time to implement, complete, test, and stabilize. However, barring any serious complications, the goal is to release the new public version before Christmas.

**Comment by bumbaras** [comment] 2024-11-11 11:45
I wonder, is this GraalVM something implemented into MangaDownloader and it needs full JDK to be operational or is it something installed with full JDK?

**Comment by RedSquirrel87** [comment] 2024-11-11 12:37
> I wonder, is this GraalVM something implemented into MangaDownloader and it needs full JDK to be operational or is it something installed with full JDK?

The first, GraalVM is implemented into MangaDownloader and requires the full JDK to be operational. It is not something that comes with the full JDK by default, but rather, it is integrated into MangaDownloader and utilizes the JDK to function properly.
GraalVM is a crucial component for running JavaScript code to decrypt content encrypted by some websites. Since MangaDownloader is a desktop application and not a web browser, it doesn't have the built-in capability to interpret JavaScript. GraalVM fills this gap, allowing MangaDownloader to handle and decrypt the necessary web content.

**Comment by bumbaras** [comment] 2024-11-12 05:09
Funny is that BatoV3 is not using this kind of encryption then. So it is similar to NodeJS?

**Comment by RedSquirrel87** [comment] 2024-12-29 11:13
v70 just released, it should fix this issue 👍

**Closed by RedSquirrel87** 2024-12-29 11:13 UTC
Labels: bug
